---

- hosts: localhost
  vars:
    ansible_python_interpreter: /usr/bin/python2.7

  vars_prompt:
  - name: "mysql_zabbix_pass"
    prompt: "Enter mysql_zabbix_pass"
    private: yes
    confirm: yes

  tasks:

  - name: ZABBIX | Copying zabbix_server.conf to /etc/zabbix/
    ansible.builtin.copy:
      src: zabbix_server.conf
      dest: /etc/zabbix/
      owner: root
      group: zabbix
      mode: '0600'
      backup: yes
    tags:
      - setup

  - name: ZABBIX | Edit file /etc/zabbix/zabbix_server.conf
    ansible.builtin.lineinfile:
        path: /etc/zabbix/zabbix_server.conf
        line: |

          DBPassword={{ mysql_zabbix_pass }}
        create: no
        owner: root
        group: zabbix
        mode: '0600'
    tags:
      - setup
  
  - name: ZABBIX | Copying zabbix.conf to /etc/opt/rh/rh-php72/php-fpm.d/
    ansible.builtin.copy:
      src: zabbix.conf
      dest: /etc/opt/rh/rh-php72/php-fpm.d/
      owner: root
      group: root
      mode: '0644'
      backup: yes
    tags:
      - setup

  - name: ZABBIX | Copying zabbix_agentd.conf to /etc/zabbix/
    ansible.builtin.copy:
      src: zabbix_agentd.conf
      dest: /etc/zabbix/
      owner: root
      group: root
      mode: '0644'
      backup: yes
    tags:
      - setup

  - name: ZABBIX | Edit file /etc/zabbix/zabbix_agentd.conf
    ansible.builtin.lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        line: |

          Hostname={{ ansible_hostname }}
        create: no
        owner: root
        group: root
        mode: '0644'
    tags:
      - setup

  - name: OPERATING SYSTEM | Restart and enable services
    ansible.builtin.systemd:
      name: "{{ item }}"
      state: restarted
      enabled: yes
    with_items:
      - zabbix-server
      - zabbix-agent
      - httpd
      - rh-php72-php-fpm
    tags:
      - services

...
