Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/focal64"

    config.vm.define "zabbix_srv" do |zabbix_srv|

        zabbix_srv.vm.network "public_network", ip: "192.168.0.50", bridge: "TP-Link Wireless MU-MIMO USB Adapter"

        zabbix_srv.vm.provision "shell", inline: "apt-get update"

        zabbix_srv.vm.provider "virtualbox" do |vb|
            vb.memory = 4096
            vb.cpus = 4
            vb.name = "zabbix_srv"
            vb.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]

        end

    end

end