version: '3'

services:

  mysql-server:
    build:
      dockerfile: ./dockerfile/mysql-server.dockerfile
      context: .
    image: mysql:8.0
    container_name: mysql-server
    networks:
      - zabbix-network

  zabbix-java-gateway:
    image: zabbix-java-gateway:alpine-5.4-latest
    restart: unless-stopped
    container_name: zabbix-java-gateway
    networks:
      - zabbix-network

  zabbix-server-mysql:
    build:
      dockerfile: ./dockerfile/zabbix-server-mysql.dockerfile
      context: .
    image: zabbix-server-mysql:alpine-5.4-latest
    restart: unless-stopped
    container_name: zabbix-server-mysql
    networks:
      - zabbix-network

  zabbix-web-nginx-mysql:
    build:
      dockerfile: ./dockerfile/zabbix-web-nginx-mysql.dockerfile
      context: .
    image: zabbix-web-nginx-mysql:alpine-5.4-latest
    restart: unless-stopped
    container_name: zabbix-web-nginx-mysql
    networks:
      - zabbix-network

networks:
  zabbix-network:
    driver: bridge