Vagrant.configure('2') do |config|
    config.vm.box = 'ubuntu/focal64'

    config.vm.define 'zabbix_srv' do |zabbix_srv|

        zabbix_srv.vm.network 'public_network', ip: '192.168.0.50', bridge: 'TP-Link Wireless MU-MIMO USB Adapter'
        zabbix_srv.vm.network 'forwarded_port', guest: 80, host:80

        zabbix_srv.vm.provision 'shell', inline: 'sudo apt-get update'
        zabbix_srv.vm.provision 'shell', inline: 'sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -'
        zabbix_srv.vm.provision 'shell', inline: 'sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"'
        zabbix_srv.vm.provision 'shell', inline: 'sudo apt-get update'
        zabbix_srv.vm.provision 'shell', inline: 'sudo apt-get install docker-ce -y'
        zabbix_srv.vm.provision 'shell', inline: 'sudo curl -L "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose'
        zabbix_srv.vm.provision 'shell', inline: 'sudo chmod +x /usr/local/bin/docker-compose'

        zabbix_srv.vm.provider 'virtualbox' do |vb|
            vb.memory = 4096
            vb.cpus = 4
            vb.name = 'zabbix_srv'
            vb.customize ['modifyvm', :id, '--nicpromisc2', 'allow-all']

        end

    end

end