Vagrant.configure('2') do |config|
    config.vm.box = 'ubuntu/focal64'

    config.vm.define 'zabbix_srv' do |zabbix_srv|

        zabbix_srv.vm.hostname = 'zabbix-srv'
        zabbix_srv.vm.network 'public_network', ip: '192.168.0.50', bridge: 'TP-Link Wireless MU-MIMO USB Adapter'
        zabbix_srv.vm.network 'forwarded_port', guest: 80, host:80
        zabbix_srv.vm.network 'forwarded_port', guest: 10051, host:10051

        zabbix_srv.vm.provision 'shell', inline: 'sudo apt-get update'
        zabbix_srv.vm.provision 'shell', inline: 'sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -'
        zabbix_srv.vm.provision 'shell', inline: 'sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"'
        zabbix_srv.vm.provision 'shell', inline: 'sudo apt-get update'
        zabbix_srv.vm.provision 'shell', inline: 'sudo apt-get install docker-ce -y'
        zabbix_srv.vm.provision 'shell', inline: 'sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose'
        zabbix_srv.vm.provision 'shell', inline: 'sudo chmod +x /usr/local/bin/docker-compose'
        zabbix_srv.vm.provision 'shell', inline: 'cd /vagrant && sudo docker-compose build'
        zabbix_srv.vm.provision 'shell', inline: 'sudo docker-compose -f /vagrant/docker-compose.yml --profile zabbix up -d'
        zabbix_srv.vm.provision 'shell', inline: 'sudo mkdir -p /home/vagrant/zabbixdb'

        zabbix_srv.vm.provider 'virtualbox' do |vb|
            vb.memory = 4096
            vb.cpus = 4
            vb.name = 'zabbix_srv'
            vb.customize ['modifyvm', :id, '--nicpromisc2', 'allow-all']

        end

    end

    config.vm.define 'awx_srv' do |awx_srv|

        awx_srv.vm.hostname = 'awx-srv'
        awx_srv.vm.network 'public_network', ip: '192.168.0.100', bridge: 'TP-Link Wireless MU-MIMO USB Adapter'
#        zabbix_srv.vm.network 'forwarded_port', guest: 80, host:80
#        zabbix_srv.vm.network 'forwarded_port', guest: 10051, host:10051

        awx_srv.vm.provision 'shell', inline: 'sudo apt-get update'
        awx_srv.vm.provision 'shell', inline: 'sudo apt-get install build-essential'
        awx_srv.vm.provision 'shell', inline: 'sudo curl -sfL https://get.k3s.io | sh -'
        awx_srv.vm.provision 'shell', inline: 'sudo export NAMESPACE=default'

        export NAMESPACE=default

        awx_srv.vm.provider 'virtualbox' do |vb|
            vb.memory = 8192
            vb.cpus = 4
            vb.name = 'awx_srv'
            vb.customize ['modifyvm', :id, '--nicpromisc2', 'allow-all']

        end

    end

end